name: CI
on:
  pull_request:
  merge_group:
  push:
    branches:
      - main

permissions:
  # Make sure package write permission is always enabled, even
  # for Dependabot pull requests.
  packages: write

# Prevent multiple runs on the same branch. This is important for webhooks
# that must be run in order.
concurrency:
  group: ${{ github.head_ref || github.ref_name }}
  cancel-in-progress: true

jobs:
  debug:
    steps:
      - name: github.ref
        run: echo "${{ github.ref }}"
      - name: github.head_ref
        run: echo "${{  github.head_ref }}"
      - name: branch
        run: echo "${{ github.event.repository.default_branch }}"

  publish-stage-image:
    if: github.head_ref == format('refs/heads/{0}', github.event.repository.default_branch)
    runs-on: "ubuntu-22.04"
    steps:
      - name: Checkout Repo
        if: ${{ github.actor != 'dependabot[bot]' }}
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
